

name: Upload E-Book Application frontend to S3

on:
  push:
    branches:
      - main
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --save ignore-warnings

      - name: Build React Application
        run: |
          CI='' npm run build
          ls -l
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy files to the test website with the AWS CLI
        run: |
          cp appspec.yml ./build
          cp -r script build
          zip -r app.zip build
          aws s3 cp app.zip s3://rexalphapi/E-Book_Frontend/
